### ISSUE TITLE
return deleted recipe

### ISSUE THREAD

**Issue by Extremator** [CreativeMD/CraftingManager#27]
I wanted to make my way to create objects of sophistication, with the help of your mod.
Everything was good, but ...

I disabled the ability to create basic objects, and it works But when I tried to disable the ability to create a thing of fashion GregTech - he hung up, but only to restart the game.

(I made a picture, for that would explain - http://cs621916.vk.me/v621916303/5ce0/qcTgY46H8Ss.jpg )
Here's what my recipe - 1, 2, 3, 4, and 5, all is well
Basic recipes 3 and 4 - were gone, leaving only mine!
Just save a recipe 5, which is good.

But in the game after restarting the remains of the old recipe 6!
And this is categorically not unusual and should be!

. . .

P.S.1: I use MC 1.6.4, and 0.6.8 versions of your mod. You could develop it further?
(I can not pereytti on 1.7+ because it will have to rebuild modpak, and the new version will be fatal changes ... it's bad)

P.S.2: Do you really not convenient GUI, I'd like to see
 - A separate list of recipes created with the possibility of on/off if necessary
 - The possibility of adding side probuktov recipe (one with a trolley-chest = Trolley, + you get the chest)
 - The ability to scroll through a list of recipes using the mouse wheel
 - The ability to create/edit recipes for oven:
 - - And similarly for grinder/macerator/shredder, extractor, compressor (IC2), sawmill, bottling plant (ThermalExpansion), and the like

. . .

Sorry for my english, I use a translator (he is not very good).

**Comment by CreativeMD** [comment]
I'm really sorry, but i don't support 1.6.4 anymore.
I focus on 1.7.10 to make a good working version: 1.0.7.
Some of your ideas are already added
- i maybe will add profiles
- i will think about side products but they are too easy to make
- don't like the idea of the mouse wheel, because if you add a recipe and scroll before you hit the save button everything is gone :(
- maybe i will add support for other mods, but i added an api for modders to add their own machines themselves
